name: Build and Test WraithBound

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true # Ensures submodules like SFML are initialized

      # Install all necessary dependencies for SFML and your project
      - name: Install Required Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential \
              libgl1-mesa-dev libglu1-mesa-dev libudev-dev \
              libopenal-dev libvorbis-dev libogg-dev libflac-dev \
              libxrandr-dev libxcursor-dev xvfb

      # Create build directory
      - name: Create Build Directory
        run: mkdir build

      # Configure the project with CMake
      - name: Configure Project
        run: cmake -B build -S . -DOPENAL_INCLUDE_DIR="/usr/include/AL" -DOPENAL_LIBRARY="/usr/lib/x86_64-linux-gnu/libopenal.so"

      # Build the project
      - name: Build Project
        run: cmake --build build --target copy_resources_release --config Release


      # List contents of the build directory
      - name: List Build Directory
        run: ls -R build/bin/Release

      # Check for the installer
      - name: Check for Installer
        run: |
          if [ -f build/bin/Release/WraithBound ]; then
            echo "Installer found."
          else
            echo "Installer not found."
            exit 1
          fi
