name: WraithBound

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Create Build Directory
      run: mkdir -p build && cd build

    - name: Configure with CMake
      run: |
        cd build
        cmake ..

    - name: Build Project
      run: |
        cd build
        cmake --build .
