name: Build and Test WraithBound

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true # Ensures submodules like SFML are initialized

      # Install dependencies
      - name: Install Build Tools and Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git
      - name: Install OpenGL
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

      # Configure the project with CMake
      - name: Configure Project
        run: cmake -B build -S .

      # Build the project
      - name: Build Project
        run: cmake --build build --config Release

      # Test the executable
      - name: Test Executable
        run: |
          if [ -f "./build/bin/GameEng" ]; then
            echo "Executable GameEng found!"
            ./build/bin/GameEng --version # Replace with an actual test command or argument for your executable
          else
            echo "Error: Executable GameEng not found."
            exit 1
          fi
