name: Build Windows Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup dependencies
    - name: Install Dependencies
      run: |
        choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' --yes
        choco install innosetup --yes
        choco install openal-soft --yes
        choco install sfml --yes

    # Configure CMake
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    # Build the project
    - name: Build Project
      run: |
        cd build
        cmake --build . --target copy_resources_release --config Release
        cmake --build . --target installer --config Release

    # Upload the installer artifact
    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: WraithBoundInstaller
        path: build/WraithBoundInstaller.exe
